title: Open Source Cloud and DevOps
description: Readup for cloud people to enjoy.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
- name: generate-sitemap
  uses: cicirello/generate-sitemap@v1.9.1

